// Traduzioni per guida_yggdrasil.html
const translationsGuidaYggdrasil = {
  en: {
    title: "Yggdrasil Guide - The Magic of Mesh Networks",
    mainTitle: "🌐 Yggdrasil Guide - The Magic of Mesh Networks",
    whatIsTitle: "🔮 What is Yggdrasil and its 'Magic'?",
    whatIsDesc: "Yggdrasil is a <strong>decentralized and secure mesh network</strong> that allows connecting devices worldwide without needing central servers, traditional VPNs, or complicated configurations. It's like technological 'magic' that creates a private global network invisible to traditional filters and protections.",
    magicList: "<strong>Yggdrasil's 'magic':</strong><ul><li>🚀 <strong>Bypass any firewall</strong> - Includes Cloudflare, national great firewalls, and advanced filtering systems</li><li>🔒 <strong>End-to-end encryption</strong> - All communications are automatically encrypted</li><li>🌍 <strong>Global access</strong> - Connect to any device on the network from anywhere</li><li>⚡ <strong>High speed</strong> - Intelligent routing that finds the most efficient paths</li><li>🕵️ <strong>Complete anonymity</strong> - No public IP address visible</li><li>🔧 <strong>Zero configuration</strong> - Self-configures and automatically finds peers</li></ul>",
    cloudflareTitle: "☁️ How we used Yggdrasil to bypass Cloudflare",
    cloudflareDesc: "Our site <strong>servicess.net</strong> is protected by Cloudflare, which is excellent for security but can block access to internal APIs. When we tried to access the delivery management system from the internet, Cloudflare intercepted all <code>/api/*</code> requests and blocked them.",
    solution: "The 'magic' solution? <strong>Yggdrasil!</strong>",
    approach: "<strong>Our approach:</strong><ol><li>Configured Yggdrasil on the server hosting the APIs (port 5504)</li><li>Modified the backend to listen on IPv6 (::) as well</li><li>Updated the frontend to use the Yggdrasil address instead of servicess.net/api</li><li>Result: Direct API access completely bypassing Cloudflare!</li></ol>",
    codeComment: "# Yggdrasil address of our server",
    codeFrontend: "# Code in the frontend",
    gestionaleTitle: "🛵 Our Intelligent Delivery Management System",
    gestionaleDesc: "We have developed a complete system for delivery management that combines <strong>artificial intelligence, advanced security, and automation</strong>.",
    dashboardTitle: "📊 Management Dashboard",
    dashboardDesc: "Complete control panel with real-time statistics, order management, rider monitoring, and user ban system.",
    aiTitle: "🤖 AI & Machine Learning",
    aiDesc: "Intelligent algorithms to optimize routes, predict delivery times, and detect suspicious behavior.",
    securityTitle: "🔐 Multi-Level Security",
    securityDesc: "Advanced CAPTCHA, multi-factor authentication, continuous monitoring, and protection from cyber attacks.",
    mobileTitle: "📱 Mobile-First System",
    mobileDesc: "Responsive interface optimized for smartphones, tablets, and desktop with real-time push notifications.",
    howWorks: "How the management system works:",
    step1: "<strong>Online Order:</strong> Customers order via app/web with geolocation",
    step2: "<strong>Intelligent Assignment:</strong> AI automatically assigns the closest rider",
    step3: "<strong>Real-Time Tracking:</strong> GPS delivery monitoring with dynamic ETA",
    step4: "<strong>Secure Payment:</strong> Integration with encrypted payment systems",
    step5: "<strong>Feedback & Ratings:</strong> Review system to improve service",
    whatWeDoTitle: "🚀 What we're doing at ServiceSS",
    whatWeDoDesc: "<strong>ServiceSS</strong> is much more than just a delivery company. We are building an <strong>ecosystem of intelligent services</strong> that combines:",
    enterpriseTitle: "🏢 Enterprise Security",
    enterpriseDesc: "AI-powered video surveillance systems, biometric access control, and 24/7 monitoring.",
    iotTitle: "🏠 IoT & Home Automation",
    iotDesc: "Smart homes with energy automation, predictive security, and remote control.",
    sysadminTitle: "🔧 System Administration",
    sysadminDesc: "Enterprise server management, secure backups, infrastructure monitoring, and cybersecurity.",
    networkingTitle: "🌐 Advanced Networking",
    networkingDesc: "Secure mesh networks, corporate VPNs, intelligent firewalls, and innovative connectivity solutions.",
    goal: "Our goal is to create <strong>cutting-edge technological solutions</strong> that solve real problems of modern businesses, always with an eye on security, privacy, and efficiency.",
    accessTitle: "🔑 How to access our Yggdrasil network",
    accessDesc: "If you want to experience Yggdrasil's 'magic' and access our services in a completely secure and private way:",
    contactFor: "<strong>Contact us for:</strong><ul><li>Yggdrasil access keys at low cost</li><li>Guided mesh network configuration</li><li>Access to delivery management system</li><li>Consulting to implement Yggdrasil in your infrastructure</li></ul>",
    conclusion: "<strong>Yggdrasil is not just a technology... it's the future of secure networks! 🌟</strong>",
    backLink: "← Back to Home"
  },
  it: {
    title: "Guida Yggdrasil - Le Magie della Rete Mesh",
    mainTitle: "🌐 Guida Yggdrasil - Le Magie della Rete Mesh",
    whatIsTitle: "🔮 Cos'è Yggdrasil e le sue \"Magie\"?",
    whatIsDesc: "Yggdrasil è una <strong>rete mesh decentralizzata e sicura</strong> che permette di connettere dispositivi in tutto il mondo senza bisogno di server centrali, VPN tradizionali o configurazioni complicate. È come una \"magia\" tecnologica che crea una rete privata globale invisibile agli occhi dei filtri e delle protezioni tradizionali.",
    magicList: "<strong>Le \"magie\" di Yggdrasil:</strong><ul><li>🚀 <strong>Bypass di qualsiasi firewall</strong> - Include Cloudflare, grandi firewall nazionali, e sistemi di filtraggio avanzati</li><li>🔒 <strong>Crittografia end-to-end</strong> - Tutte le comunicazioni sono automaticamente criptate</li><li>🌍 <strong>Accesso globale</strong> - Connettiti a qualsiasi dispositivo nella rete da qualsiasi luogo</li><li>⚡ <strong>Velocità elevata</strong> - Routing intelligente che trova i percorsi più efficienti</li><li>🕵️ <strong>Anonimato completo</strong> - Nessun indirizzo IP pubblico visibile</li><li>🔧 <strong>Zero configurazione</strong> - Si auto-configura e trova automaticamente i peer</li></ul>",
    cloudflareTitle: "☁️ Come abbiamo usato Yggdrasil per bypassare Cloudflare",
    cloudflareDesc: "Il nostro sito <strong>servicess.net</strong> è protetto da Cloudflare, che è eccellente per la sicurezza ma può bloccare l'accesso alle API interne. Quando abbiamo provato ad accedere al gestionale delle consegne da internet, Cloudflare intercettava tutte le richieste <code>/api/*</code> e le bloccava.",
    solution: "La soluzione \"magica\"? <strong>Yggdrasil!</strong>",
    approach: "<strong>Il nostro approccio:</strong><ol><li>Configurato Yggdrasil sul server che ospita le API (porta 5504)</li><li>Modificato il backend per ascoltare anche su IPv6 (::)</li><li>Aggiornato il frontend per usare l'indirizzo Yggdrasil invece di servicess.net/api</li><li>Risultato: Accesso diretto alle API bypassando completamente Cloudflare!</li></ol>",
    codeComment: "# Indirizzo Yggdrasil del nostro server",
    codeFrontend: "# Codice nel frontend",
    gestionaleTitle: "🛵 Il nostro Gestionale Consegne Intelligente",
    gestionaleDesc: "Abbiamo sviluppato un sistema completo per la gestione delle consegne che combina <strong>intelligenza artificiale, sicurezza avanzata e automazione</strong>.",
    dashboardTitle: "📊 Dashboard Gestionale",
    dashboardDesc: "Pannello di controllo completo con statistiche in tempo reale, gestione ordini, monitoraggio rider e sistema di ban utenti.",
    aiTitle: "🤖 AI & Machine Learning",
    aiDesc: "Algoritmi intelligenti per ottimizzare le rotte, prevedere i tempi di consegna e rilevare comportamenti sospetti.",
    securityTitle: "🔐 Sicurezza Multi-Livello",
    securityDesc: "CAPTCHA avanzato, autenticazione a più fattori, monitoraggio continuo e protezione da attacchi informatici.",
    mobileTitle: "📱 Sistema Mobile-First",
    mobileDesc: "Interfaccia responsive ottimizzata per smartphone, tablet e desktop con notifiche push in tempo reale.",
    howWorks: "Come funziona il gestionale:",
    step1: "<strong>Ordine Online:</strong> I clienti ordinano tramite app/web con geolocalizzazione",
    step2: "<strong>Assegnazione Intelligente:</strong> L'AI assegna automaticamente il rider più vicino",
    step3: "<strong>Tracking Real-Time:</strong> Monitoraggio GPS della consegna con ETA dinamica",
    step4: "<strong>Pagamento Sicuro:</strong> Integrazione con sistemi di pagamento criptati",
    step5: "<strong>Feedback & Valutazioni:</strong> Sistema di recensioni per migliorare il servizio",
    whatWeDoTitle: "🚀 Cosa stiamo facendo in ServiceSS",
    whatWeDoDesc: "<strong>ServiceSS</strong> è molto più di una semplice azienda di consegne. Stiamo costruendo un <strong>ecosistema di servizi intelligenti</strong> che combina:",
    enterpriseTitle: "🏢 Sicurezza Aziendale",
    enterpriseDesc: "Sistemi di videosorveglianza AI-powered, controllo accessi biometrici e monitoraggio 24/7.",
    iotTitle: "🏠 Domotica & IoT",
    iotDesc: "Case intelligenti con automazione energetica, sicurezza predittiva e controllo remoto.",
    sysadminTitle: "🔧 System Administration",
    sysadminDesc: "Gestione server enterprise, backup sicuri, monitoraggio infrastruttura e cybersecurity.",
    networkingTitle: "🌐 Networking Avanzato",
    networkingDesc: "Reti mesh sicure, VPN aziendali, firewall intelligenti e soluzioni di connettività innovativa.",
    goal: "Il nostro obiettivo è creare <strong>soluzioni tecnologiche all'avanguardia</strong> che risolvano problemi reali delle aziende moderne, sempre con un occhio di riguardo alla sicurezza, alla privacy e all'efficienza.",
    accessTitle: "🔑 Come accedere alla nostra rete Yggdrasil",
    accessDesc: "Se vuoi sperimentare le \"magie\" di Yggdrasil e accedere ai nostri servizi in modo completamente sicuro e privato:",
    contactFor: "<strong>Contattaci per:</strong><ul><li>Chiavi di accesso Yggdrasil a basso costo</li><li>Configurazione guidata della rete mesh</li><li>Accesso al gestionale delle consegne</li><li>Consulenza per implementare Yggdrasil nella tua infrastruttura</li></ul>",
    conclusion: "<strong>Yggdrasil non è solo una tecnologia... è il futuro delle reti sicure! 🌟</strong>",
    backLink: "← Torna alla Home"
  }
};