// Traduzioni per straordinarie.html
const translations = {
  it: {
    title: "Pulizie Straordinarie - Servicess.net",
    header: "Pulizie Straordinarie",
    subtitle: "Servizio di pulizia profonda per ambienti speciali",
    cosa_include: "Cosa include il servizio",
    pulizia_profonda: "Pulizia profonda: Rimozione di sporco accumulato, polvere e macchie difficili.",
    disinfezione: "Sanificazione: Utilizzo di prodotti ecologici per sanificare l'ambiente.",
    trattamento_superfici: "Trattamento superfici speciali: Pavimenti, pareti, mobili e aree critiche.",
    personale_qualificato: "Personale qualificato: Operatori esperti con attrezzature professionali.",
    rapporto_finale: "Rapporto finale: Documentazione fotografica e certificato di pulizia.",
    prezzo: "Prezzo",
    pulizia_base: "Pulizia base (fino a 100mq)",
    pulizia_completa: "Pulizia completa (fino a 200mq)",
    disinfezione_extra: "Sanificazione extra",
    come_funziona: "Come funziona",
    step1: "Contattaci per una valutazione gratuita",
    step2: "Definiamo il servizio e il preventivo",
    step3: "Eseguiamo la pulizia in sicurezza",
    step4: "Ricevi il certificato e le foto",
    genera_contratto: "Genera Contratto",
    nome_cliente: "Nome Cliente",
    numero_operatori: "Numero Operatori",
    ore_giorno: "Ore al giorno",
    numero_giorni: "Numero Giorni",
    data_inizio: "Data Inizio",
    genera_pdf: "Genera PDF Contratto",
    richiedi_preventivo: "Richiedi un preventivo per Pulizie Straordinarie",
    contattaci: "Contattaci"
  },
  en: {
    title: "Extraordinary Cleanings - Servicess.net",
    header: "Extraordinary Cleanings",
    subtitle: "Deep cleaning service for special environments",
    cosa_include: "What the service includes",
    pulizia_profonda: "Deep cleaning: Removal of accumulated dirt, dust and difficult stains.",
    disinfezione: "Sanitization: Use of ecological products to sanitize the environment.",
    trattamento_superfici: "Special surface treatment: Floors, walls, furniture and critical areas.",
    personale_qualificato: "Qualified personnel: Experienced operators with professional equipment.",
    rapporto_finale: "Final report: Photographic documentation and cleaning certificate.",
    prezzo: "Price",
    pulizia_base: "Basic cleaning (up to 100sqm)",
    pulizia_completa: "Complete cleaning (up to 200sqm)",
    disinfezione_extra: "Extra sanitization",
    come_funziona: "How it works",
    step1: "Contact us for a free assessment",
    step2: "We define the service and quote",
    step3: "We perform the cleaning safely",
    step4: "Receive the certificate and photos",
    genera_contratto: "Generate Contract",
    nome_cliente: "Client Name",
    numero_operatori: "Number of Operators",
    ore_giorno: "Hours per day",
    numero_giorni: "Number of Days",
    data_inizio: "Start Date",
    genera_pdf: "Generate PDF Contract",
    richiedi_preventivo: "Request a quote for Extraordinary Cleanings",
    contattaci: "Contact Us"
  },
  es: {
    title: "Limpiezas Extraordinarias - Servicess.net",
    header: "Limpiezas Extraordinarias",
    subtitle: "Servicio de limpieza profunda para ambientes especiales",
    cosa_include: "Qué incluye el servicio",
    pulizia_profonda: "Limpieza profunda: Remoción de suciedad acumulada, polvo y manchas difíciles.",
    disinfezione: "Sanificación: Uso de productos ecológicos para sanificar el ambiente.",
    trattamento_superfici: "Tratamiento de superficies especiales: Pisos, paredes, muebles y áreas críticas.",
    personale_qualificato: "Personal calificado: Operadores experimentados con equipos profesionales.",
    rapporto_finale: "Informe final: Documentación fotográfica y certificado de limpieza.",
    prezzo: "Precio",
    pulizia_base: "Limpieza básica (hasta 100m²)",
    pulizia_completa: "Limpieza completa (hasta 200m²)",
    disinfezione_extra: "Sanificación extra",
    come_funziona: "Cómo funciona",
    step1: "Contáctanos para una evaluación gratuita",
    step2: "Definimos el servicio y el presupuesto",
    step3: "Realizamos la limpieza de forma segura",
    step4: "Recibe el certificado y las fotos",
    genera_contratto: "Generar Contrato",
    nome_cliente: "Nombre del Cliente",
    numero_operatori: "Número de Operadores",
    ore_giorno: "Horas al día",
    numero_giorni: "Número de Días",
    data_inizio: "Fecha de Inicio",
    genera_pdf: "Generar PDF del Contrato",
    richiedi_preventivo: "Solicita un presupuesto para Limpiezas Extraordinarias",
    contattaci: "Contáctanos"
  },
  fr: {
    title: "Nettoyages Extraordinaires - Servicess.net",
    header: "Nettoyages Extraordinaires",
    subtitle: "Service de nettoyage en profondeur pour environnements spéciaux",
    cosa_include: "Ce que comprend le service",
    pulizia_profonda: "Nettoyage en profondeur: Suppression de la saleté accumulée, poussière et taches difficiles.",
    disinfezione: "Sanitisation: Utilisation de produits écologiques pour sanitiser l'environnement.",
    trattamento_superfici: "Traitement des surfaces spéciales: Planchers, murs, meubles et zones critiques.",
    personale_qualificato: "Personnel qualifié: Opérateurs expérimentés avec équipements professionnels.",
    rapporto_finale: "Rapport final: Documentation photographique et certificat de nettoyage.",
    prezzo: "Prix",
    pulizia_base: "Nettoyage de base (jusqu'à 100m²)",
    pulizia_completa: "Nettoyage complet (jusqu'à 200m²)",
    disinfezione_extra: "Sanitisation supplémentaire",
    come_funziona: "Comment ça marche",
    step1: "Contactez-nous pour une évaluation gratuite",
    step2: "Nous définissons le service et le devis",
    step3: "Nous effectuons le nettoyage en toute sécurité",
    step4: "Recevez le certificat et les photos",
    genera_contratto: "Générer Contrat",
    nome_cliente: "Nom du Client",
    numero_operatori: "Nombre d'Opérateurs",
    ore_giorno: "Heures par jour",
    numero_giorni: "Nombre de Jours",
    data_inizio: "Date de Début",
    genera_pdf: "Générer PDF du Contrat",
    richiedi_preventivo: "Demandez un devis pour Nettoyages Extraordinaires",
    contattaci: "Contactez-nous"
  },
  de: {
    title: "Außergewöhnliche Reinigungen - Servicess.net",
    header: "Außergewöhnliche Reinigungen",
    subtitle: "Tiefenreinigungsservice für spezielle Umgebungen",
    cosa_include: "Was der Service beinhaltet",
    pulizia_profonda: "Tiefenreinigung: Entfernung von angesammeltem Schmutz, Staub und schwierigen Flecken.",
    disinfezione: "Sanitisierung: Verwendung ökologischer Produkte zur Sanitisierung der Umgebung.",
    trattamento_superfici: "Spezielle Oberflächenbehandlung: Böden, Wände, Möbel und kritische Bereiche.",
    personale_qualificato: "Qualifiziertes Personal: Erfahrene Bediener mit professioneller Ausrüstung.",
    rapporto_finale: "Abschlussbericht: Fotodokumentation und Reinigungszertifikat.",
    prezzo: "Preis",
    pulizia_base: "Grundreinigung (bis 100m²)",
    pulizia_completa: "Vollständige Reinigung (bis 200m²)",
    disinfezione_extra: "Zusätzliche Sanitisierung",
    come_funziona: "Wie es funktioniert",
    step1: "Kontaktieren Sie uns für eine kostenlose Bewertung",
    step2: "Wir definieren den Service und das Angebot",
    step3: "Wir führen die Reinigung sicher durch",
    step4: "Erhalten Sie das Zertifikat und die Fotos",
    genera_contratto: "Vertrag Generieren",
    nome_cliente: "Kundenname",
    numero_operatori: "Anzahl der Bediener",
    ore_giorno: "Stunden pro Tag",
    numero_giorni: "Anzahl der Tage",
    data_inizio: "Startdatum",
    genera_pdf: "PDF-Vertrag Generieren",
    richiedi_preventivo: "Fordern Sie ein Angebot für Außergewöhnliche Reinigungen an",
    contattaci: "Kontaktieren Sie uns"
  },
  ar: {
    title: "تنظيفات استثنائية - Servicess.net",
    header: "تنظيفات استثنائية",
    subtitle: "خدمة تنظيف عميق للبيئات الخاصة",
    cosa_include: "ما يشمل الخدمة",
    pulizia_profonda: "التنظيف العميق: إزالة الأوساخ المتراكمة، الغبار والبقع الصعبة.",
    disinfezione: "التعقيم: استخدام منتجات بيئية لتعقيم البيئة.",
    trattamento_superfici: "معالجة الأسطح الخاصة: الأرضيات، الجدران، الأثاث والمناطق الحرجة.",
    personale_qualificato: "الموظفين المؤهلين: مشغلون ذوو خبرة مع معدات احترافية.",
    rapporto_finale: "التقرير النهائي: التوثيق الفوتوغرافي وشهادة التنظيف.",
    prezzo: "السعر",
    pulizia_base: "التنظيف الأساسي (حتى 100 متر مربع)",
    pulizia_completa: "التنظيف الكامل (حتى 200 متر مربع)",
    disinfezione_extra: "تعقيم إضافي",
    come_funziona: "كيف يعمل",
    step1: "اتصل بنا لتقييم مجاني",
    step2: "نحدد الخدمة والميزانية",
    step3: "نقوم بالتنظيف بأمان",
    step4: "احصل على الشهادة والصور",
    genera_contratto: "إنشاء عقد",
    nome_cliente: "اسم العميل",
    numero_operatori: "عدد المشغلين",
    ore_giorno: "ساعات في اليوم",
    numero_giorni: "عدد الأيام",
    data_inizio: "تاريخ البدء",
    genera_pdf: "إنشاء PDF للعقد",
    richiedi_preventivo: "اطلب عرض أسعار للتنظيفات الاستثنائية",
    contattaci: "اتصل بنا"
  },
  ru: {
    title: "Экстраординарные уборки - Servicess.net",
    header: "Экстраординарные уборки",
    subtitle: "Услуга глубокой уборки для специальных помещений",
    cosa_include: "Что включает услуга",
    pulizia_profonda: "Глубокая уборка: Удаление накопившейся грязи, пыли и трудных пятен.",
    disinfezione: "Санитизация: Использование экологических продуктов для санитизации окружающей среды.",
    trattamento_superfici: "Специальная обработка поверхностей: Полы, стены, мебель и критические зоны.",
    personale_qualificato: "Квалифицированный персонал: Опытные операторы с профессиональным оборудованием.",
    rapporto_finale: "Итоговый отчет: Фотодокументация и сертификат уборки.",
    prezzo: "Цена",
    pulizia_base: "Базовая уборка (до 100 кв.м)",
    pulizia_completa: "Полная уборка (до 200 кв.м)",
    disinfezione_extra: "Дополнительная санитизация",
    come_funziona: "Как это работает",
    step1: "Свяжитесь с нами для бесплатной оценки",
    step2: "Мы определяем услугу и смету",
    step3: "Мы проводим уборку безопасно",
    step4: "Получите сертификат и фото",
    genera_contratto: "Создать Контракт",
    nome_cliente: "Имя Клиента",
    numero_operatori: "Количество Операторов",
    ore_giorno: "Часы в день",
    numero_giorni: "Количество Дней",
    data_inizio: "Дата Начала",
    genera_pdf: "Создать PDF Контракта",
    richiedi_preventivo: "Запросите смету для Экстраординарных Уборок",
    contattaci: "Свяжитесь с нами"
  },
  zh: {
    title: "特别清洁 - Servicess.net",
    header: "特别清洁",
    subtitle: "针对特殊环境的深度清洁服务",
    cosa_include: "服务包括什么",
    pulizia_profonda: "深度清洁：去除积聚的污垢、灰尘和难处理的污渍。",
    disinfezione: "消毒：使用生态产品消毒环境。",
    trattamento_superfici: "特殊表面处理：地板、墙壁、家具和关键区域。",
    personale_qualificato: "合格人员：经验丰富的操作员配备专业设备。",
    rapporto_finale: "最终报告：摄影文档和清洁证书。",
    prezzo: "价格",
    pulizia_base: "基本清洁（最多100平方米）",
    pulizia_completa: "完整清洁（最多200平方米）",
    disinfezione_extra: "额外消毒",
    come_funziona: "如何运作",
    step1: "联系我们进行免费评估",
    step2: "我们定义服务和报价",
    step3: "我们安全地进行清洁",
    step4: "接收证书和照片",
    genera_contratto: "生成合同",
    nome_cliente: "客户姓名",
    numero_operatori: "操作员数量",
    ore_giorno: "每天小时",
    numero_giorni: "天数",
    data_inizio: "开始日期",
    genera_pdf: "生成PDF合同",
    richiedi_preventivo: "请求特别清洁报价",
    contattaci: "联系我们"
  },
  ja: {
    title: "特別清掃 - Servicess.net",
    header: "特別清掃",
    subtitle: "特殊環境向けの深層清掃サービス",
    cosa_include: "サービスの内容",
    pulizia_profonda: "深層清掃：蓄積した汚れ、埃、難しい汚れの除去。",
    disinfezione: "消毒：環境を消毒するためのエコ製品の使用。",
    trattamento_superfici: "特殊表面処理：床、壁、家具、重要な領域。",
    personale_qualificato: "資格のある人員：プロの機器を備えた経験豊富なオペレーター。",
    rapporto_finale: "最終レポート：写真ドキュメントと清掃証明書。",
    prezzo: "価格",
    pulizia_base: "基本清掃（最大100平方メートル）",
    pulizia_completa: "完全清掃（最大200平方メートル）",
    disinfezione_extra: "追加消毒",
    come_funziona: "どのように機能するか",
    step1: "無料評価のために連絡してください",
    step2: "サービスと見積りを定義します",
    step3: "安全に清掃を行います",
    step4: "証明書と写真を受け取る",
    genera_contratto: "契約を生成",
    nome_cliente: "クライアント名",
    numero_operatori: "オペレーター数",
    ore_giorno: "1日あたりの時間",
    numero_giorni: "日数",
    data_inizio: "開始日",
    genera_pdf: "PDF契約を生成",
    richiedi_preventivo: "特別清掃の見積りをリクエスト",
    contattaci: "お問い合わせ"
  },
  hi: {
    title: "असाधारण सफाई - Servicess.net",
    header: "असाधारण सफाई",
    subtitle: "विशेष वातावरण के लिए गहरी सफाई सेवा",
    cosa_include: "सेवा में क्या शामिल है",
    pulizia_profonda: "गहरी सफाई: जमा हुए गंदगी, धूल और कठिन धब्बों को हटाना।",
    disinfezione: "स्वच्छता: पर्यावरण को स्वच्छ करने के लिए पारिस्थितिक उत्पादों का उपयोग।",
    trattamento_superfici: "विशेष सतह उपचार: फर्श, दीवारें, फर्नीचर और महत्वपूर्ण क्षेत्र।",
    personale_qualificato: "योग्य कर्मचारी: पेशेवर उपकरणों के साथ अनुभवी ऑपरेटर।",
    rapporto_finale: "अंतिम रिपोर्ट: फोटो दस्तावेजीकरण और सफाई प्रमाणपत्र।",
    prezzo: "मूल्य",
    pulizia_base: "बुनियादी सफाई (100 वर्ग मीटर तक)",
    pulizia_completa: "पूर्ण सफाई (200 वर्ग मीटर तक)",
    disinfezione_extra: "अतिरिक्त स्वच्छता",
    come_funziona: "यह कैसे काम करता है",
    step1: "मुफ्त मूल्यांकन के लिए हमसे संपर्क करें",
    step2: "हम सेवा और बजट को परिभाषित करते हैं",
    step3: "हम सुरक्षित रूप से सफाई करते हैं",
    step4: "प्रमाणपत्र और फोटो प्राप्त करें",
    genera_contratto: "अनुबंध उत्पन्न करें",
    nome_cliente: "ग्राहक का नाम",
    numero_operatori: "ऑपरेटरों की संख्या",
    ore_giorno: "दिन में घंटे",
    numero_giorni: "दिनों की संख्या",
    data_inizio: "प्रारंभ तिथि",
    genera_pdf: "PDF अनुबंध उत्पन्न करें",
    richiedi_preventivo: "असाधारण सफाई के लिए बजट का अनुरोध करें",
    contattaci: "हमसे संपर्क करें"
  }
};

function setStraordinarieLanguage(lang) {
  console.log('Cambiando lingua a:', lang);
  const t = translations[lang] || translations['it'];
  console.log('Traduzioni caricate:', Object.keys(t).length);
  document.title = t.title;
  document.querySelector('h1').textContent = t.header;
  document.querySelectorAll('h2')[0].textContent = t.subtitle;
  document.querySelectorAll('h2')[1].textContent = t.cosa_include;
  document.querySelectorAll('li')[0].textContent = t.pulizia_profonda;
  document.querySelectorAll('li')[1].textContent = t.disinfezione;
  document.querySelectorAll('li')[2].textContent = t.trattamento_superfici;
  document.querySelectorAll('li')[3].textContent = t.personale_qualificato;
  document.querySelectorAll('li')[4].textContent = t.rapporto_finale;
  document.querySelectorAll('h2')[2].textContent = t.prezzo;
  document.querySelectorAll('li')[5].textContent = t.pulizia_base;
  document.querySelectorAll('li')[6].textContent = t.pulizia_completa;
  document.querySelectorAll('li')[7].textContent = t.disinfezione_extra;
  document.querySelectorAll('h2')[3].textContent = t.come_funziona;
  document.querySelectorAll('li')[8].textContent = t.step1;
  document.querySelectorAll('li')[9].textContent = t.step2;
  document.querySelectorAll('li')[10].textContent = t.step3;
  document.querySelectorAll('li')[11].textContent = t.step4;
  document.querySelector('h3').textContent = t.genera_contratto;
  document.querySelector('label[for="nome_cliente"]').textContent = t.nome_cliente;
  document.querySelector('label[for="numero_operatori"]').textContent = t.numero_operatori;
  document.querySelector('label[for="ore_giorno"]').textContent = t.ore_giorno;
  document.querySelector('label[for="numero_giorni"]').textContent = t.numero_giorni;
  document.querySelector('label[for="data_inizio"]').textContent = t.data_inizio;
  document.querySelector('button[type="submit"]').textContent = t.genera_pdf;
  document.querySelectorAll('h2')[4].textContent = '👉 ' + t.richiedi_preventivo;
  document.querySelector('.btn').textContent = t.contattaci;
}
