# Generated by Django 5.2.6 on 2025-09-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('file_id', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tattoos',
            },
        ),
    ]
